import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/layout/menu";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={cn("rounded-md flex flex-col md:flex-row w-full flex-1 border overflow-hidden", "h-screen")}>
          <Menu />
          <main className="p-5 w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
